farmguru/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',  # noqa
        TemplateView.as_view(template_name='base.html'),
        name="home"),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name="about"),
    url(r'^animals/', include('animals.urls')),
    url(r'^groups/', include('groups.urls')),
    url(r'^finances/', include('finances.urls')),
    url(r'^records/', include('records.urls')),
    url(r'^health/', include('health.urls')),

    url(r'^users/', include('smartmin.users.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),

    # RapidSMS core URLs
    (r'^accounts/', include('rapidsms.urls.login_logout')),
    url(r'^$', 'rapidsms.views.dashboard', name='rapidsms-dashboard'),
    # RapidSMS contrib app URLs
    (r'^httptester/', include('rapidsms.contrib.httptester.urls')),
    #(r'^locations/', include('rapidsms.contrib.locations.urls')),
    (r'^messagelog/', include('rapidsms.contrib.messagelog.urls')),
    (r'^messaging/', include('rapidsms.contrib.messaging.urls')),
    (r'^registration/', include('rapidsms.contrib.registration.urls')),

    # Third party URLs
    (r'^selectable/', include('selectable.urls')),

    (r'^select2/', include('django_select2.urls')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farmguru/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
    # URL pattern for the UserListView  # noqa
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
)

farmguru/animals/models.py
from django.db import models
from django.utils.translation import ugettext as _
from model_utils.models import TimeStampedModel
from model_utils import Choices


class Breed(TimeStampedModel):
    name = models.CharField(max_length=30)
    gestation_period = models.IntegerField(max_length=4)


class Animal(TimeStampedModel):
    # Choices
    STATUS_CHOICES = Choices(('active', _('Active')), )
    COLOR_CHOICES = Choices(('yellow', _('Yellow')), )
    GENDER_CHOICES = Choices(('bull', _('Bull')), ('cow', _('Cow')))

    # Identification
    animal_id = models.CharField(max_length=30, blank=True)
    alt_id = models.CharField(max_length=30, blank=True)
    electronic_id = models.CharField(max_length=30, blank=True)
    ear_tag = models.CharField(max_length=30, blank=False)
    name = models.CharField(max_length=30, blank=True)

    # Description
    color = models.CharField(choices=COLOR_CHOICES, max_length=20, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=20)
    breed = models.ForeignKey(Breed, null=True, blank=True)
    sire = models.ForeignKey('self', null=True, blank=True, related_name='animal_sire')
    dam = models.ForeignKey('self', null=True, blank=True, related_name='animal_dam')

    # Status
    status = models.CharField(choices=STATUS_CHOICES, default=STATUS_CHOICES.active, max_length=20, blank=True)

    # Calfhood
    birth_date = models.DateField(null=True, blank=True)
    birth_weight = models.IntegerField(max_length=4, null=True, blank=True)
    weaning_date = models.DateField(null=True, blank=True)
    weaning_weight = models.IntegerField(max_length=4, null=True, blank=True)
    yearling_date = models.DateField(null=True, blank=True)
    yearling_weight = models.IntegerField(max_length=4, null=True, blank=True)

    def __unicode__(self):
        return self.ear_tag

farmguru/users/models.py
# -*- coding: utf-8 -*-
# Import the AbstractUser model
from django.contrib.auth.models import AbstractUser

# Import the basic Django ORM models library
from django.db import models

from django.utils.translation import ugettext_lazy as _


# Subclass AbstractUser
class User(AbstractUser):

    def __unicode__(self):
        return self.username

farmguru/templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
  {% load bootstrap3 %}
  <title>{% block title %} Farmguru {% endblock %}</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Google Font: Open Sans -->
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,800,800italic">
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300,700">

  <!-- Font Awesome CSS -->
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <!-- App CSS -->
  <link rel="stylesheet" href="{% static 'css/mvpready-admin-belize.css' %}">
  <link rel="stylesheet" href="{% static 'css/mvpready-flat.css' %}">
  <link rel="stylesheet" href="{% static 'css/farmguru.css' %}">

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <script src="{% static 'js/libs/jquery-1.10.2.min.js' %}"></script>
    <!-- blueimp Gallery styles -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/blueimp-gallery/2.15.0/css/blueimp-gallery.min.css">
    <!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
    <link rel="stylesheet" href="{% static 'js/plugins/djupload/css/jquery.fileupload-ui.css' %}">
    <!-- CSS adjustments for browsers with JavaScript disabled -->
    <noscript><link rel="stylesheet" href="{% static 'js/plugins/djupload/jquery.fileupload-ui-noscript.css' %}"></noscript>


  {% block extra-style %}{% endblock %}

</head>

<body class=" ">

<div id="wrapper">

  {% block header %}
    {% include "partials/header.html" %}
  {% endblock %}

  <div class="content">

    <div class="container">
        <div class="row">
            <h2 class="">{% block page_title %}{% endblock %}</h2>
        </div>
        {% bootstrap_messages %}

        {% block content %} {% endblock %}

    </div> <!-- /.container -->

  </div> <!-- .content -->

</div> <!-- /#wrapper -->

<footer class="footer">
  <div class="container">
    <p class="pull-left">Copyright &copy; 2015 farmguru.</p>
  </div>
</footer>


{# compress js #}

<script src="{% static 'js/libs/bootstrap.min.js' %}"></script>

<!--[if lt IE 9]>
<script src="{% static 'js/libs/excanvas.compiled.js' %}"></script>
<![endif]-->

<!-- App JS -->
<script src="{% static 'js/mvpready-core.js' %}"></script>
<script src="{% static 'js/mvpready-admin.js' %}"></script>

{% block extra-script %}{% endblock %}

{# media associated with any form we are displaying #}
{% if form %}
{{ form.media }}
{% endif %}

{% block script %}{% endblock %}
{# endcompress #}

</body>
</html>

farmguru/templates/base0.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}farmguru{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% block angular %}
      <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js"></script>
    {% endblock %}
<!-- blueimp Gallery styles -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/blueimp-gallery/2.15.0/css/blueimp-gallery.min.css">
    <!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
    <link rel="stylesheet" href="{% static 'js/plugins/djupload/jquery.fileupload-ui.css' %}">
    <!-- CSS adjustments for browsers with JavaScript disabled -->
    <noscript><link rel="stylesheet" href="{% static 'js/plugins/djupload/jquery.fileupload-ui-noscript.css' %}"></noscript>




  </head>

  <body>

    <div class="header navbar">
      <div class="container">
        <a class="navbar-brand" href="/">farmguru</a>
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'about' %}">About</a></li>

          {% if request.user.is_authenticated %}
            <li><a href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a></li>
            <li><a href="{% url 'account_logout' %}">{% trans "Logout" %}</a></li>
          {% else %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
            <li><a href="{% url 'account_login' %}">{% trans "Log In" %}</a></li>
          {% endif %}
        </ul>
      </div>
    </div>

    <div class="container">
        
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->
    
    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  {% block extra-script %}{% endblock %}
  </body>
</html>
 

farmguru/templates/base_sangoma.html
<!DOCTYPE html>
<!--[if IE 8]>    <html class="no-js ie8 ie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9 ie" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<title>{% block title %} Farmguru {% endblock %}</title>
		<meta name="description" content="">
		<meta name="author" content="Farmguru Team">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		{% load staticfiles %}
        <!-- JS Libs -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/libs/jquery.js"><\/script>')</script>
        {% load bootstrap3 %}
        {# Load CSS and JavaScript #}
        {# Load CSS and JavaScript #}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
		<!-- PrettyCheckable Styles -->
		<link rel='stylesheet' type='text/css' href='{{ STATIC_URL }}css/plugins/prettycheckable/prettyCheckable.css'>

		<!-- Styles -->
		<link rel="stylesheet" href="{{ STATIC_URL }}css/sangom-orange.css">

        <link rel="stylesheet" href="{{ STATIC_URL }}css/custm.css">


		<!-- IE8 support of media queries and CSS 2/3 selectors -->
	</head>
	<body>

		<!-- Full height wrapper -->
		<div id="wrapper">

			<!-- Main page header -->
			<header id="header" class="container">

				<h1>
					<!-- Main page logo -->
					<a href="/" class="brand">farmguru</a>

				</h1>

				<!-- User profile -->
				<div class="user-profile">
					<figure>

						<!-- User profile avatar
						<img alt="avatar" src="">
						 -->
						<!-- User profile info -->

						<!-- /User profile info -->

					</figure>
				</div>
		<!-- /Full height wrapper -->

				<!-- /User profile -->
                <!-- Main navigation -->
				<nav class="main-navigation navbar navbar-default" role="navigation">

					<!-- Collapse navigation for mobile -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".main-navigation-collapse">
							<span class="elusive icon-file"></span> Online store
						</button>
					</div>
					<!-- /Collapse navigation for mobile -->

					<!-- Navigation -->
					<div class="main-navigation-collapse collapse navbar-collapse">

						<!-- Navigation items -->
						<ul class="nav navbar-nav">

							<li>
								<a href="{% url 'animals.animal_list' %}">Livestock</a>
							</li>


							<!-- Dropdown navigation items -->

							<!-- /Dropdown navigation items -->

							<!-- Dropdown navigation with multi-level dropdown -->

							<!-- /Dropdown navigation with multi-level dropdown -->

							<li>
								<a href="{% url "account_logout" %}"><span class="elusive icon-lock-alt"></span> Logout</a>
							</li>
						</ul>
						<!-- /Navigation items -->


					</div>
					<!-- /Navigation -->

				</nav>
				<!-- /Main navigation -->



			</header>
			<!-- /Main page header -->

			<!-- Main page container -->
			<section class="container" role="main">
			<!-- Grid row -->
				<div class="row">
                {% bootstrap_messages %}
                {% block secondary_menu %} {% endblock %}

                <!-- Data block -->
                <article class="col-sm-12">
                    <div class="green data-block">
                        <header>
                            <h2>{% block header %}{% endblock %}</h2>
                            <ul class="data-header-actions">
                                {% block header_actions %}{% endblock %}
                            </ul>
                        </header>

                        <section>
                            <div class="row">
                                {% block content %}

                                {% endblock %}
                            </div>
                        </section>

                    </div>
                </article>
        </div>
	 	<!-- Main page footer
		<footer id="footer">
			<div class="container">

				<!-- Footer info
				<p>&copy; farmguru</p>
				<!-- Footer back to top
				<a href="#top" class="btn btn-alt"><span class="icon-arrow-up"></span></a>

			</div>
		</footer>
		<!-- /Main page footer -->

    </div>
      {# compress js #}
      <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.pjax.js"></script>
      <script type="text/javascript" src="{{ STATIC_URL }}js/scripts.js"></script>
      <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.min.js"></script>


      {% block extra-script %}{% endblock %}

      {# media associated with any form we are displaying #}
      {% if form %}
      {{ form.media }}
      {% endif %}

      {% block script %}{% endblock %}
      {# endcompress #}

	</body>
</html>

farmguru/templates/base_smartmin.html
<!doctype html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Farmguru{% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
  <link rel="icon" type="image/x-icon" href="{{ STATIC_URL }}img/favicon.ico">

  <!-- CSS: implied media="all" -->
  {# load compress #}
  {# compress css #}
  {% block styles %}
  <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.css">
  <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-theme.css">
  <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/smartmin_styles.css">
  <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/styles.css">
  <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/project.css">
  {% endblock %}

  {% block extra-style %}{% endblock %}

  {# endcompress #}
</head>

<body>

  {% block navbar %}
  <header class="navbar navbar-static-top navbar-inverse" role="banner">
    <div class="container">

      <div class="navbar-header">
	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#smartmin-navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
	</button>

	{% block brand %}
	<a class="navbar-brand" href="/">Farmguru</a>
	{% endblock brand %}
      </div>

      {% block navigation %}
      <nav class="collapse navbar-collapse" id="smartmin-navbar-collapse" role="navigation">
	<ul class="nav navbar-nav">
	  {% if perms.nsms.text_list %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Configuration<b class="caret"></b></a>
              <ul class="dropdown-menu">
		{% if perms.auth.user_list %}
		<li><a href="/users/user/">Users</a></li>
		{% endif %}
              </ul>
            </li>
          {% endif %}
	</ul>

	<ul class="nav navbar-nav navbar-right">
	  {% block login %}
          {% if request.user and request.user.is_authenticated %}
          <li>
            <a href="{% url 'users.user_profile' request.user.id %}" style="float: left;">{{ request.user.username }}</a>
            <a href="{% url 'users.user_logout' %}?go=/" style="float: right;">logout</a>
          </li>
          {% else %}
          <li><a href="{% url 'users.user_login' %}">Login</a></li>
          {% endif %}
          {% endblock login %}
	</ul>
      </nav>
      {% endblock navigation %}

    </div>

  </header>
  {% endblock navbar %}

  <div class="container">

    {% load smartmin %}

    {% block content-div %}
    <div class="content">
      {% block messages %}
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        <a class="close" data-dismiss="alert">×</a>
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
      {% endblock messages %}

      {% block pre-content %}
      {% endblock %}

      {% block content %}
      {% endblock %}

      {% block post-content %}
      {% endblock %}
    </div>
    {% endblock %}

    <footer>
      {% block footer %}
      <a href="http://www.nyaruka.com/"><div class="pull-right" id="footer"></div></a>
      {% endblock %}
    </footer>

  </div> <!-- /container -->

  <!-- JavaScript at the bottom for fast page loading, conditional based on whether we are serving locally -->
  <script>
    if (window.location.hostname == "localhost"){
    document.write(unescape('%3Cscript src="{{ STATIC_URL }}js/libs/jquery.1.11.1.min.js"%3E%3C/script%3E'));
    } else {
    document.write(unescape('%3Cscript src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"%3E%3C/script%3E'));
    }
  </script>

  {# compress js #}
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.pjax.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/scripts.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.min.js"></script>

  {# media associated with any form we are displaying #}
  {% if form %}
  {{ form.media }}
  {% endif %}

  {% block extra-script %}{% endblock %}
  {% block script %}{% endblock %}
  {# endcompress #}

  <!-- mathiasbynens.be/notes/async-analytics-snippet Change UA-XXXXX-X to be your site's ID -->
  <!--script type="text/javascript">
      var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
      g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g,s)}(document,'script'));
      </script-->

</body>
</html>

farmguru/templates/rapidsms_base.html
{% load url from future %}
{% load i18n %}
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">{# keep this right after <head> #}
        <title>{% block title %}RapidSMS{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% block stylesheets %}
{#        <link type="text/css" rel="stylesheet" href="{% static 'rapidsms/stylesheets/tables.css' %}" />#}
        <link type="text/css" rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'rapidsms/stylesheets/base.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-responsive.css' %}" />
        {% endblock %}

        {% block extra_stylesheets %}
        {% endblock %}

        {% block javascripts %}
        <script type="text/javascript" src="{% static 'rapidsms/javascripts/jquery-1.9.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'rapidsms/javascripts/collapse.js' %}"></script>
        <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        {% endblock %}
        {% block extra_javascript %}
        {% endblock %}
    </head>

    <body>
        <div id="wrap">  {# Wrap everything but the footer so we can push the footer to the bottom #}

            {% block header %}
                <div class="navbar navbar-blue navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container">

                            {# .btn-navbar is used as the toggle for collapsed navbar content #}
                            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </a>

                            {# Be sure to leave the brand out there if you want it shown #}
                            <a href="/" class="brand">
                                <img alt="RapidSMS Logo" width="100" src="{% static 'rapidsms/images/rapidsms-logo.png' %}"/>
                            </a>

                            {#  Everything you want hidden at 940px or less, place within here #}
                            <div class="nav-collapse collapse">
                                <ul class="nav">
                                    {% include "rapidsms/_nav_bar.html" %}
                                </ul>
                                <ul class="nav pull-right">
                                    {% block admin_link %}
                                        {% if user.is_staff %}
                                            <li>
                                                <a href="{% url 'admin:index' %}">{% trans "Admin" %}</a>
                                            </li>
                                        {% endif %}
                                    {% endblock %}
                                    {% block login_link %}
                                        <li>
                                            {% block auth %}
                                                {% if user.is_authenticated %}
                                                    <a href="{% url 'rapidsms-logout' %}">{% trans "Log out" %} {{ user.username }}</a>
                                                {% else %}
                                                    <a href="{% url 'rapidsms-login' %}">{% trans "Log in" %}</a>
                                                {% endif %}
                                            {% endblock auth %}
                                        </li>
                                    {% endblock %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% block page_tabs %}{# FIXME - putting anything here won't do anything useful. If anything is using page_tabs, we should probably move this up into the navbar collapsable area. #}
                {% endblock %}
            {% endblock %}

            {# begin page content - has its own div container so we can add top padding  #}
            <div class="container" id="mainpage">
                {% block breadcrumbs %}{% if breadcrumbs %}
                    <div class="row-fluid">{% for caption, url in breadcrumbs %}
                        <a href="{{ url }}">{{ caption }}</a>{% if not forloop.last %}
                        <span>&raquo;</span>{% endif %}{% endfor %}
                    </div>{% endif %}
                {% endblock %}

                {% block messages %}
                  <div id="messages">
                    {% for message in messages %}
                      <div class="alert{% if message.tags %} alert-{{ message.tags }}"{% endif %}>
                         <a class="close" data-dismiss="alert" href="#">&times;</a>
                        {{ message }}
                      </div>
                     {% endfor %}
                  </div>
                {% endblock messages %}

                <div class="row-fluid content">
                    {% block content %}{% endblock %}
                </div>
            </div>
            <div id="push"></div>{# important to push footer down #}
        </div>{# end wrap - everything above the footer #}


            <div id="footer">
                <div class="container">
                    {% block footer %}
                        <div class="row-fluid">
                            {# if the height of this changes, the CSS in base.css will have to be changed to match #}
                            <p>
                                Copyright &copy; 2008 &#8211; 2015
                                <a href="http://unicef.org">UNICEF</a> et al.<br />
                                <a href="http://github.com/rapidsms/rapidsms">RapidSMS</a> is available under
                                <a href="http://github.com/rapidsms/rapidsms/raw/master/LICENSE">the BSD license</a>.
                            </p>
                        </div>
                    {% endblock footer %}
                </div>
            </div>
    </body>
</html>